#!/usr/local/bin/perl

package wifrss;

$main::action_plugin{'rss'} = sub {

my $URL=sprintf('http://%s%s', $ENV{'HTTP_HOST'} , $ENV{'SCRIPT_NAME'} );
my $RSS="$URL?a=rss";
my $articles=3;

%::enclist = (
    'lp'       => '&#40;' ,
    'rp'       => '&#41;' ,
    'lb'       => '&#91;' ,
    'rb'       => '&#93;' ,
    'll'       => '&#40;&#40;' ,
    'rr'       => '&#41;&#41;' ,
    'vl'       => '&#124;' ,
);

my %config;
my $pwdfn='__' . unpack("h*",'password');
open(FP,"<$pwdfn"  ) || die("Can not open $pwdfn");
while( <FP> ){
    if( /^(\S+)\t(.*)$/ ){
	$config{$1} = $2;
    }
}
close(FP);

my $sitename=$config{sitename};

print qq(Content-Type: text/plane; charset=EUC-JP\n\n);

### read page list ###
my @pagelist;
opendir(DIR,".") || die;
while( my $fn=readdir(DIR) ){
    next unless $fn =~ /^[a-z0-9]+$/;
    my $title = pack("h*",$fn); 
    next unless $title =~ /^\(\d\d\d\d\.\d\d\.\d\d\)/;
    push( @pagelist , { fname=>$fn , title=>$title } );
}
closedir(DIR);
@pagelist = sort{ $a->{title} cmp $b->{title} } @pagelist;
splice(@pagelist,0,-$articles);

print qq(<?xml version="1.0" encoding="EUC-JP" ?>
<rdf:RDF 
  xmlns="http://purl.org/rss/1.0/"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" 
  xml:lang="ja">
 <channel rdf:about="${RSS}">
  <title>${sitename}</title>
  <link>${URL}</link>
  <description>${sitename}</description>
  <items>
   <rdf:Seq>
);

### read title list ###
my @topics;
foreach my $p (@pagelist){
    open(FP,$p->{fname}) || die;
    my @text = <FP>;
    close(FP);
    my $text = join('',@text);

    local $/="\n\n";

    my $topics=[];
    my $title=$p->{title};
    my $pageurl = $title;
    my $id=0;
    $pageurl =~ s/([^\w])/sprintf('%%%02X', unpack('C', $1))/eg;
    my $desc=[];
    foreach my $frag ( split(/\r?\n\r?\n/,$text) ){
	if( $frag =~ /^\s*<<([^<].*)>>\s*$/s || $frag =~ /^!!!(.*)$/s ){
	    if( scalar(@{$desc}) > 0 ){
		my $text = join('',@{$desc});
		$text =~ s/(\r?\n)+\r?\n\r?\n/\n\n/g;
		$text =~ s/\(\(.*?\)\)//gs;
		unshift(@topics , { 
		    page  => $p->{title} ,
		    url   => sprintf("%s?p=%s#p%d",$URL,$pageurl,++$id),
		    title => sprintf("%s - %s",$p->{title},$title) ,
		    desc  => $text
		});
	    }
	    $title = $1;
	    $desc = [];
	}else{
	    push(@{$desc},$frag);
	}
    }
    if( scalar(@{$desc}) > 0 ){
	my $text = join('',@{$desc});
	$text =~ s/\r?\n\r?\n\r?\n/\n\n/g;
	$text =~ s/\(\(.*?\)\)//gs;
	unshift(@topics , { 
	    page => $p->{title} ,
	    url => sprintf("%s?p=%s#p%d",$URL,$pageurl,++$id),
	    title => sprintf("%s - %s",$p->{title},$title) ,
	    desc => $text
	});
    }
}

### write list ###
foreach my $t (@topics){
    printf qq(<rdf:li rdf:resource="%s"/>\n),$t->{url} ;
}
print "</rdf:Seq>\n";
print "</items>\n";
print "</channel>\n";

### write description ###
foreach my $t (@topics){
    printf qq(<item rdf:about="%s">\n),$t->{url} ;
    printf qq(<title>%s</title>\n),&enc($t->{title}) ;
    printf qq(<link>%s</link>\n),$t->{url} ;
    printf qq(<description>\n%s\n</description>\n),&::enc($t->{desc}) ;
    printf qq(</item>\n);
}
print "</rdf:RDF>\n";

exit(0);

};

sub enc{
    my $s=shift;
    $s =~ s/^\s+//;
    $s =~ s/</\&lt;/g;
    $s =~ s/>/\&gt;/g;
    $s =~ s/&/\&amp;/g;
    $s =~ s/'//g;
    $s =~ s/\s+$//;
    $s =~ s/\(\((.*?)\)\)/&wifrss::encsub($1)/ge;
    $s;
}

sub encsub{
    my $s=shift;
    exists $enclist{$s} ? $enclist{$s} : '';
}

1;
